name: example
description: A sample script to checkout mdb_dart package.
version: 1.0.0

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  mdb_dart: ^0.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
