name: mdb_dart
description: MindsDB SDK for Dart for efficient interaction.
version: 0.0.1
repository: https://github.com/ArnavK-09/mdb_dart

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  dart_openai: ^5.1.0
  # path: ^1.8.0

dev_dependencies:
  dartenv: ^1.0.2
  lints: ^5.0.0
  test: ^1.24.0
