name: mdb_dart
description:  A powerful and intuitive SDK for interacting with the Minds AI API. Seamlessly integrate machine learning capabilities into your Dart applications!
version: 0.0.3
repository: https://github.com/ArnavK-09/mdb_dart
homepage: https://arnavk-09.github.io/mdb_dart/

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  dart_openai: ^5.1.0
  # path: ^1.8.0

dev_dependencies:
  dartenv: ^1.0.2
  lints: ^5.0.0
  test: ^1.24.0
