name: 🕸 Deploy Dart Docs on Github Pages...

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: dart pub get

      - name: Generate documentation
        run: dart doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./doc/api"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
